baseURL: https://jyotsi.com/
languageCode: en-us
title: Jyotsi

theme: PaperMod

params:
    defaultTheme: dark
    disableThemeToggle: true
    label: 
        icon: "logo.svg"
        iconHeight: "60px"
        text: " "
    
    homeInfoParams:
        Title: Welcome to Jyotsi !
        Content: "Our mission is simple - Provide Data Insights"
